export const LISTEN_TO_CURRENT_USER_PROFILE = "LISTEN_TO_CURRENT_USER_PROFILE";
export const LISTEN_TO_SELECTED_USER_PROFILE =
  "LISTEN_TO_SELECTED_USER_PROFILE";
export const LISTEN_TO_USER_EVENT = "LISTEN_TO_USER_EVENT";
export const LISTEN_TO_FOLLOWERS = "LISTEN_TO_FOLLOWERS";
export const LISTEN_TO_FOLLOWINGS = "LISTEN_TO_FOLLOWINGS";
export const LISTEN_FOLLOW_USER = "LISTEN_FOLLOW_USER";
export const LISTEN_UNFOLLOW_USER = "LISTEN_UNFOLLOW_USER";
export const CLEAR_FOLLOWER = "CLEAR_FOLLOWER";
